### ISSUE TITLE
The latest NFT included in music-os-accumulator was apparently minted at block number 14624411

### ISSUE THREAD

**Issue by TimDaub** [neume-network/data#15]
- For each track in results/music-os-accumulator, given the latest branch on strategies, I've included a `createdAt` property and started sorting the songs. I found that the latest track is from block 14624411
- https://etherscan.io/block/14624411 was mined on Apr-20-2022 09:42:00 PM +UTC
- For at least Zora/catalog tracks, this lack of new songs can be explained by them switching to their V2 contract
- But what about Sound? Weren't there truly any more songs minted on sound since April 20? Do we have a problem in the crawl?

/cc @il3ven @reimertz

**Comment by il3ven** [comment]
In the latest crawl at https://github.com/neume-network/data/commit/5f4b1083cc5d45e27fca43fb058caf48dcba9159 web3subgraph crawled till block number 15167797. However in music-os-accumulator this block number is missing.

The highest block (i.e. 15167797) belongs to a Zora contract. This is the NFT given by web3subgraph. `{"address":"0xabefbc9fd2f806065b4f3c237d4b59d9a97bcac7","tokenId":"22119","createdAtBlockNumber":"15167797","platform":"zora"}`

Upon digging through the data I found that the above NFT is present in [zora-call-tokenuri-extraction](https://raw.githubusercontent.com/neume-network/data/main/results/zora-call-tokenuri-extraction) but absent from [zora-call-tokenuri-transformation](https://raw.githubusercontent.com/neume-network/data/main/results/zora-call-tokenuri-transformation).

I checked through the logs and there weren't any errors or anything suspicious.

My theory is that zora-call-tokenuri-transformation is called before zora-call-tokenuri-extraction gets completed. This is similar to the problem discussed at https://github.com/neume-network/strategies/issues/154#issuecomment-1170385860. The fact supporting this theory is that number of lines in zora-call-tokenuri-extraction does not equal zora-call-tokenuri-transformation. They should be equal. If we were doing any external calls during transformation then I would understand that some calls failed and those NFTs were not written. However, this is not the case in transformation.

If my theory is correct then neume-network/strategies#168 should solve the problem.

**Comment by il3ven** [comment]
If we remove `version.includes("catalog")` from here then we do get more NFTs.

https://github.com/neume-network/strategies/blob/9c2f6c8a7ee95d9f035a5e9e2722c7fc7b4dd654/src/strategies/music-os-accumulator/extractor.mjs#L151

Currently NFTs such as below are omitted by the music-os accumulator.

tokenId: `19134`, address: `0xabefbc9fd2f806065b4f3c237d4b59d9a97bcac7`, createdAtBlock: `15000054`, metadata: `{"description":"The happy time between son and father","mimeType":"image/png","name":"Fatherly love","version":"zora-20210101"}`

@TimDaub Is this behaviour intentional? I am not sure.

**Comment by TimDaub** [comment]
> tokenId: `19134`, address: `0xabefbc9fd2f806065b4f3c237d4b59d9a97bcac7`, createdAtBlock: `15000054`, metadata: `{"description":"The happy time between son and father","mimeType":"image/png","name":"Fatherly love","version":"zora-20210101"}`

The tokenURI of that NFT is https://ipfs.io/ipfs/bafkreianqlf5wuvgwlz6d46ktz7utfoiygubtpuqrmae5ijeyaswegrdi4 and so I believe it's not an audio file we're currently interested in for music-os.

**Comment by TimDaub** [comment]
Putting this issue back on the top priority.

A few more data points:

- Catalog has moved to V2 a separate contract
  - This issue covers it: https://github.com/neume-network/strategies/issues/34 
  - THe web3-subgraph supports catalogv2 indexing too: https://github.com/neume-network/web3-music-subgraph/tree/main/src/catalogV2
- However, why have there been no new releases for soundxyz since 106 days? https://etherscan.io/block/14624411

**Comment by TimDaub** [comment]
If we sort yesterday's https://github.com/neume-network/data/blob/b6583c8384d93d1015dad9d3584addb5661c4d84/results/soundxyz-call-tokenuri-extraction soundxyz-call-tokenuri-extraction by block numbers, we also find that the last song is from block 14624411

**Comment by TimDaub** [comment]
For soundxyz, I'm able to track down the issue: https://github.com/neume-network/web3-music-subgraph/issues/1

**Comment by il3ven** [comment]
For zora we are getting this error.

```
2022-08-04T14:45:30.686Z neume-network-extraction-worker:worker Panic in queue with taskId "b2e92d15-ccc8-4cc7-89ca-19c565df69c7", error "{"type":"json-rpc","commissioner":"zora-call-tokenmetadatauri","options":{"url":"***","signal":{}},"version":"0.0.1","method":"eth_call","params":[{"from":null,"to":"0xabefbc9fd2f806065b4f3c237d4b59d9a97bcac7","data":"0x157c3df90000000000000000000000000000000000000000000000000000000000004bd6"},"0xe5a51a"],"metadata":{"block":{"number":"15050225"},"contract":{"address":"0xabefbc9fd2f806065b4f3c237d4b59d9a97bcac7"},"tokenId":"19414"},"results":null,"error":"RPCError: Error from fullnode: execution reverted: Media: token with that id does not exist"}" and stats "{"elapsed":1001690}"
```

From: https://github.com/neume-network/data/runs/7674323762?check_suite_focus=true#step:3:10784

This should be because we have fixed block number while making call to `eth_call`.

**Comment by TimDaub** [comment]
Yeah but again, I'm not expecting any new music NFTs to emerge from zora as catalog switched to their own contract.

**Comment by il3ven** [comment]
This now seems to be a combination of web3subgraph not indexing soundxyz and Catalog moving to V2. Correct me if I am wrong. Nothing is wrong with our current implementation.

**Comment by TimDaub** [comment]
It's correct. I guess that this means for us is that we should update our strategies to ingest their latest contracts

**Comment by TimDaub** [comment]
Cross post from discord

Here's a problem description about soundxyz that I wanted to put into words. I'm gonna try to "show" instead of "telling":

- They have a repository called "protocol" that contains no "protocol" (as e.g. compared to EIP-20). Factually, it contains Solidity files: https://github.com/soundxyz/protocol
- It has a surprisingly short git history that only goes back to April 26: https://github.com/soundxyz/protocol/commits/master But they had pushed code out since January: https://sound.mirror.xyz/WlS2nfpa1Onk8uknbC7YkhVJ4cYibTc4rUDTyiR55lM
- There are already five major versions of Artist.sol contracts: https://github.com/soundxyz/protocol/tree/master/contracts
- The contracts generally don't contain feature detection with e.g. EIP-165 to allow an indexer to understand which functionality is available and which isn't
- A few days ago for all NFTs, they started to break an API endpoint. We've filed an issue: https://github.com/soundxyz/protocol/issues/101
- All of their artist's contracts are upgradable: https://etherscan.io/address/0x28b708ee88e608f3307a7d41b930312fc9c9e632#code meaning that if someone writes code to crawl them, they could change them and break the crawler API
- The subgraph repository of sound hasn't been updated since 1 Feburary: https://github.com/soundxyz/subgraph
- However, the subgraph API used to serve their website arguably includes updates from new artist contracts in soundxyz/protocol: https://api.sound.xyz/graphql So this suggests that there is an internal subgraph repository and an external one
- From what I understand, no guarantees are being provided to external users for using https://api.sound.xyz/graphql I can't find any page that says: "Hey developer, feel free to use our API" Usually, this means that a developer shouldn't use an API.
- Indexer operators like Spinamp are NOT crawling the music NFT metadata from the chain directly. They are using the (internal) API: https://github.com/spinamp/spindexer/blob/main/src/clients/sound.ts

**Comment by TimDaub** [comment]
This can now be solved by talking the results of call-block-logs-transformation and building on top of them and not the web3 music subgraph
