### ISSUE TITLE
given `scripts/lastBlockNumber` and a network call to an Ethereum node, determine start and end parameters of call-block-logs-extraction step

### ISSUE THREAD

**Issue by TimDaub** [neume-network/data#29]
- we'd like to define these two variables: https://github.com/neume-network/strategies/blob/f301db569ec9b8ba1b234363c16dc56a15737b21/src/strategies/call-block-logs/extractor.mjs#L42

**Comment by il3ven** [comment]
Will it make sense to have a script let's call it _updateCallBlockParameters_ for now that calls `scripts/lastBlockNumber` to get _start_ and an Ethereum node to get _end_ and then write it as a JSON to a file? The crawl path file can read the JSON.

**Comment by TimDaub** [comment]
yeah, I've implemented something like that here: https://github.com/neume-network/data/blob/main/scripts/generateBlockLogsCrawlPath and I forgot to close the issue
