### ISSUE TITLE
when the new NFT IDs get appended to the old NFT IDs in logs-to-subgraph, and then a downstream strategy like soundxyz-call-tokenuri gets called: It sees the entire huge file and recrawls everything and not just the delta

### ISSUE THREAD

**Issue by TimDaub** [neume-network/data#36]
- see this crawl: https://github.com/neume-network/data/runs/8100361709?check_suite_focus=true
- for call-block-logs and logs-to-subgraph we happily just add to the file we prior download from neume-network/data/results
- and while the code in /scripts/ makes sure that we only pass a certain block range to call-block-logs, at the time we get to soundxyz-call-tokenuri, its presented with the entire event log of logs-to-subgraph-transformation and not just the small delta we downloaded
- So it'll start downloading all 20k tracks when it probably was only 3 or even zero during that time
- Hence, in .github, we have to run a crawl once on new files while generating the zeroth step crawl path from the neume-network/data/result/call-block-logs-transformation step
- After completing the entire crawl, we then append all the new results with `cat` to the data in neume-network/data/results and commit+push it back

**Comment by il3ven** [comment]
I thought this would be taken care of automatically. From what I understand, the data directory contains only the delta. Whereas, the neume-network-data/results directory will contain all the old NFT IDs. soundxyz-call-tokenuri should read from the data directory and it will get only the delta.

**Comment by TimDaub** [comment]
https://github.com/neume-network/data/blob/main/.github/actions/run_step/action.yml#L75

yes I think the current main branch already fixes this but there is a problem with strategies that expect files to be there when no NFT ids were found as e.g. documented here: https://github.com/neume-network/strategies/issues/251

**Comment by TimDaub** [comment]
I've just hypothetically hard coded that case: https://github.com/neume-network/data/blob/main/scripts/generateBlockLogsCrawlPath#L5 could be that the 10min crawl would already work if everytime a zora and sound nft was present
