### ISSUE TITLE
Since we now don't have steps in Github actions we can use a single crawl path

### ISSUE THREAD

**Issue by il3ven** [neume-network/data#40]
We can remove the less descriptive crawl paths such as 0.mjs, 1.mjs etc.

**Comment by TimDaub** [comment]
True, I have already started here: https://github.com/neume-network/data/tree/integrations/steps

But the 0.mjs step is still created using the bash scripts. We probably need to start working on an orchestrator to properly fix this issue I imagine...

**Comment by TimDaub** [comment]
now in main branch
