### ISSUE TITLE
the `lastBlockNumber` script doesn't work

### ISSUE THREAD

**Issue by il3ven** [neume-network/data#46]
The `lastBlockNumber` script reads the last line from call-block-logs-transformation and parses the block number from there. We have a _gotcha_ here. The lines in call-block-logs-transformation are not in sequence. This is because of extraction-worker.

- Exhibit A:
  [Action #347](https://github.com/neume-network/data/runs/8271722126?check_suite_focus=true#step:10:31): This action ran from block number 15501918, 15503120.
- Exhibit B: 
  [Action #348](https://github.com/neume-network/data/runs/8272540865?check_suite_focus=true#step:10:31): This action ran from block number 15502933 to 15503292. It should have ran from 15503121.
- Exhibit C:
These are the last two lines of call-block-logs-transformation from 5ae839b4773e220f4f92d003a1c717931f33e7e7. The second last line has a higher block number than the last line.
  ```
  [{"metadata":{"platform":{"name":"sound"}},"log":{"address":"0x08056544987f28d3134fe4ce48a8002ec1bfc277","blockHash":"0x7c03949298dfd98361304550e3afde8da244cf5052bcad7744e8f5094e2634f7","blockNumber":"0xec8e55","data":"0x","logIndex":"0x5f","removed":false,"topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x0000000000000000000000000000000000000000000000000000000000000000","0x000000000000000000000000f95a7c6504f284ada554f89b1abe9f3b0dd0595b","0x000000000000000000000000000000030000000000000000000000000000001d"],"transactionHash":"0x4b00f707738e34e4c0fffdf36ac11c215b40c3cebb8b3740d5464b4970a0b05f","transactionIndex":"0x21"}}]
  [{"metadata":{"platform":{"name":"sound"}},"log":{"address":"0xaa0647818717230b74aea9ba711566132f224847","blockHash":"0x815db9118b98267b376280335c66aa5076fb6a9c1b95f862a0e9e869a61cb509","blockNumber":"0xec8e54","data":"0x","logIndex":"0x15f","removed":false,"topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x0000000000000000000000000000000000000000000000000000000000000000","0x000000000000000000000000f95a7c6504f284ada554f89b1abe9f3b0dd0595b","0x0000000000000000000000000000000400000000000000000000000000000009"],"transactionHash":"0xb53b64af5bcecec5bf1eecac139ea2b0ef71f6314abe511cc0f07f6d3b0ba7c4","transactionIndex":"0x5d"}}]
  ```

Possible solution:
- Write the last block number in a file and read it from there.
- Modify extraction-worker to maintain sequence.

I don't like the latter solution because it is a lot of work for a problem that can be fixed with an easier solution.

**Comment by TimDaub** [comment]
great find

**Comment by TimDaub** [comment]
other possible solutions:

- iterate through the entire file and always keep the largest found blockNumber in a variable
- if along the way, a smaller block number is found, don't write it in the variable
- print the variable when reaching the end of the file
