### ISSUE TITLE
we should only update `lastBlockNumber` file with valid block numbers

### ISSUE THREAD

**Issue by il3ven** [neume-network/data#58]
It can be that the `generateBlockNumber` script fails and returns a non integer block number. Committing this incorrect block number can make all the newer crawl fail. This happened in cd1acbc54e68de9cec801131c4ee365a4b60d996.

Validate block number before updating `lastBlockNumber`. It should be an hexadecimal integer and greater than the block number already present in the file.

**Comment by TimDaub** [comment]
https://github.com/neume-network/data/commit/22e19da60b8ecb620212adbbd53c8aa7c9d76fe3 happened here too
